name: Monthly Caddy Build and Release

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号 00:00（UTC）触发
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: linux, goarch: amd64, goamd64: v3, output: amd64-v3}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        check-latest: true

    - name: Install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build Caddy with plugins
      env:
        GOOS: ${{matrix.jobs.goos}}
        GOARCH: ${{matrix.jobs.goarch}}
        GOAMD64: ${{matrix.jobs.goamd64}}
      run: |
        DATE=$(date +'%Y-%m-%d')
        VERSION="$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r '.tag_name')"
        xcaddy build \
          --with github.com/caddyserver/forwardproxy
        mkdir -p dist
        mv caddy caddy-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
        tar -czvf dist/caddy-${{matrix.jobs.goos}}-${{matrix.jobs.output}}-${VERSION}.tar.gz caddy-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
        rm caddy-${{matrix.jobs.goos}}-${{matrix.jobs.output}}
        echo "RELEASE_TAG=${VERSION}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Monthly Build (${DATE})" >> $GITHUB_ENV

    - name: Create or Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        files: dist/*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
